### ISSUE TITLE
Use decorator module for signature-preserving decorators

### ISSUE THREAD

**Issue by OOPMan** [argaen/aiocache#212]
It looks like your awesome `cached` and `multi_cached` decorators don't make use of https://pypi.python.org/pypi/decorator which helpers write cleaner decorators that benefit from signature-preservation (which is important to some people :-)

I could submit a PR if you like?

**Comment by argaen** [comment]
Hi @OOPMan, do you have an example use case, if possible I would prefer to use https://docs.python.org/3/library/functools.html#functools.wraps rather than adding a new dependency :)

**Comment by OOPMan** [comment]
@argaen I believe you can achieve the same with wraps (In fact, I think decorator does use wrap to some extent) but there's more work involved.

Honestly, I wouldn't consider this a high priority, it's just something I've run into now and then with certain code trying to implement the concept of interfaces in Python and checking that functions conform to the interface (IIRC, this is a thing in the Zope part of the Python world). When you decorate such a function non a non-signature preserving way the interface nonsense complains because a function which was `a(b,c,d,e)` is now `a(*args, **kwargs)`

It's really rather silly :-)

**Comment by argaen** [comment]
I'm happy to add the `functools.wraps` part. Once I have the MR I can ping you to see if there is anything you are missing :)

**Comment by OOPMan** [comment]
@argaen Sure
