### ISSUE TITLE
aioredis 0.3.1 Pool compatibility

### ISSUE THREAD

**Issue by dmzkrsk** [argaen/aiocache#262]
Is compatibility with `aioredis==0.3.1` planned?
They had some refactor of `Pool` class and it doesn't work with current `aiocache` version.

`requirements.txt` also specify `aioredis==0.3.1` (but `setup.py` still refers to `0.3.0`)

**Comment by argaen** [comment]
> it doesn't work with current aiocache version

What do you mean by that? I've installed `aioredis==0.3.1` and all tests are passing. Good catch though that `setup.py` is not updated with that, need to fix it

**Comment by dmzkrsk** [comment]
Oops, sorry. It must be `aioredis` master
So it's not relevant until the next release

**Comment by argaen** [comment]
Yup, indeed its master, I've seen the incompatibility problems too. Once the release for aioredis comes I'll open the issue to work on the upgrade :)
