### ISSUE TITLE
sync/async compatibility

### ISSUE THREAD

**Issue by argaen** [argaen/aiocache#268]
Issue to explore sync/async compatibility.

My simple thought about that for now is to create a mixing for the cache classes that would detect if we are in a `Task` or not. If we are, we will run normally with await, if not we will run using `loop.run_until_complete` call.

This has drawbacks:

- will add a bit of overhead
- I don't know if there are edge cases with futures, callbacks, etc. Its something I have to explore
- How to run the tests for both async and sync cases? (SUPER difficult this one)
- What about decorators? Also need to support decorating both sync/async functions... 
- No compatibility for other async models (trio, curio, etc). This for me is super minor because aioredis and aiomcache are asyncio only.

More info: https://mail.python.org/pipermail/async-sig/2017-June/000242.html

**Comment by argaen** [comment]
https://gist.github.com/argaen/056a43b083a29f76ac6e2fa97b3e08d1

**Comment by N-Coder** [comment]
FYI: There's some pretty interesting (but also quite long) [discussion](https://github.com/urllib3/urllib3/issues/1323) going on in the urllib3 repo on how to support synchronous and asynchronous operation with a single code base. Hopefully, their work will develop into some reusable library one day.

**Comment by argaen** [comment]
Ha! yeah I'm aware, been a while since the last time I read it, will have to catch up :)

**Comment by rspadim** [comment]
News?

**Comment by argaen** [comment]
I'm closing this issue as it's a topic I'm not looking at anymore. Seeing things like https://github.com/encode/httpx/blob/master/httpx/_client.py where there are two different implementations for sync/async it's not a path I'm interested on going for.
