### ISSUE TITLE
multi_cached function  got multiple values error

### ISSUE THREAD

**Issue by Artgyk** [argaen/aiocache#327]
python: 3.6.0
aiocache: 0.7.2

```  
    @multi_cached('ids', ttl=10)
    async def get_async(ids):
        return {1: '1', 2: '2'}
    res = await get_async([1, 2])
```

 File "\Python36-32\lib\site-packages\aiocache\decorators.py", line 250, in decorator
    result = await f(*new_args, **kwargs)
TypeError: get_async() got multiple values for argument 'ids'

Same as this issue:
https://github.com/argaen/aiocache/issues/270

**Comment by argaen** [comment]
I'm able to reproduce. Will have a look, thanks for reporting
