### ISSUE TITLE
aiocache compatible with aioredis 1.0.0b2

### ISSUE THREAD

**Issue by masipcat** [argaen/aiocache#345]
I created pull request #344 which implements support for aioredis 0.3.3 and 1.0.0b2.

**Comment by argaen** [comment]
Closed with https://github.com/argaen/aiocache/pull/344

**Comment by argaen** [comment]
Reopening, tests don't pass with aioredis==1.0.0b2.

If you run `make ut` you'll see tests failing (25 with current master status).
