### ISSUE TITLE
No way to release pool connection when using decorator and aiohttp

### ISSUE THREAD

**Issue by kivsiak** [argaen/aiocache#352]
When i use `@cache` decorator in my aiohttp application and close app using ctrl-C i got this message in output:

>Task was destroyed but it is pending!

Not critical, but dirty. Is there any way to clear close all connection and courtines? In aiohttp cleanup handler?

**Comment by argaen** [comment]
Hi @kivsiak, yup its a known issue. There is manual way of doing this if you really need it.

Any function that you decorate will have an attribute called `cache`: https://github.com/argaen/aiocache/blob/master/aiocache/decorators.py#L50. In your cleanup handler, you can do `await my_decorated_function.close().

**Comment by kivsiak** [comment]
Hello @argaen, looks like i'm bad at decoration, but here the gist:

https://gist.github.com/kivsiak/b2fc47008f1cdc01bd4d08359ccfc2d8

cached_call after decoration have no _cache, cache, close() attributes.

**Comment by argaen** [comment]
You are right, with the current implementation the cache is not accessible through the decorated function.

By adding a `wrapper.cache = self.cache` in https://github.com/argaen/aiocache/blob/master/aiocache/decorators.py#L67 should be enough.

Do you want to provide MR for this? (should include tests + docs updated).

**Comment by argaen** [comment]
Next release this will be avaible as `function.cache`
