### ISSUE TITLE
use @multi_cached get error when method return None

### ISSUE THREAD

**Issue by qq453655422** [argaen/aiocache#366]
when i used @multi_cached, if this method return None,i got an error

**Comment by argaen** [comment]
This is expected behavior, functions decorated with `multi_cached` are expected to return a dict.

If that's not your case please provide more data with your crash, else I'll close this issue :)

**Comment by qq453655422** [comment]
thinks, get it. can you give me a demo about how to use @multi_cached param key_builder. i am new in python

**Comment by qq453655422** [comment]
this is my code
`
import asyncio
import aiocache
from aiocache import multi_cached, RedisCache
from aiocache.serializers import PickleSerializer


aiocache.caches.set_config({
    'default': {
        'cache': "aiocache.RedisCache",
        'endpoint': "127.0.0.1",
        'port': 6379,
    },
})
async def test():
    new_a = 'onfire'
    await multi_cached_ids(new_a)

def key_builder_func(key, *args):
    print('key_builder_func')
    print(args[0])
    return 'uptown'


@multi_cached("keys", ttl=30, cache=RedisCache, key_builder=key_builder_func, namespace="main", serializer=PickleSerializer())
async def multi_cached_ids(keys=None):
    data = {'uptown': keys}
    print('multi_cached_ids')
    print(keys)
    return data

cache = aiocache.caches.get("default")


def test_multi_cached():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test())
    loop.run_until_complete(cache.close())


if __name__ == "__main__":
    test_multi_cached()
`
what i got 
`
/usr/local/bin/python3.6 /Users/python/test/work/test.py
key_builder_func
onfire
key_builder_func
onfire
key_builder_func
onfire
key_builder_func
onfire
key_builder_func
onfire
key_builder_func
onfire
multi_cached_ids
['uptown', 'uptown', 'uptown', 'uptown', 'uptown', 'uptown']
key_builder_func
onfire

Process finished with exit code 0
`
key_builder_func has be called many times

**Comment by argaen** [comment]
Problem is that you're passing a string into `keys`. If you want to pass a single key, do it with `['key']`
