### ISSUE TITLE
MsgPack exception - use_list=False

### ISSUE THREAD

**Issue by ahopkins** [argaen/aiocache#380]
I know you removed the `use_list` option in the `loads` method when deserializing. See #370 

However, I think it should be added back, even with an overwritable default. Without it, it **will** cause a difficult to diagnose exception. 

Second, I see you added the `encoding` option. It looks like that is being depracated: https://github.com/msgpack/msgpack-python#deprecating-encoding-option

I would suggest going back to 

```python
    @classmethod
    def loads(cls, value, use_list=False):
        """
        Deserialize value using ``msgpack.loads``.

        :param value: bytes
        :returns: obj
        """
        if value is None:
            return None
        return msgpack.loads(value, use_list=use_list)
```

Furthermore, I am trying to use it with a simple string loaded serializer: `aiocache.serializers.MsgPackSerializer`. Which, to me means adding some sensible defaults.

    {
        'cache': "aiocache.RedisCache",
        'serializer': {
            'class': "aiocache.serializers.MessagePackSerializer"
        },
        'plugins': [
            {'class': "aiocache.plugins.HitMissRatioPlugin"},
            {'class': "aiocache.plugins.TimingPlugin"}
        ],
    }

**Comment by argaen** [comment]
Hi, I'm working on https://github.com/argaen/aiocache/pull/379. This will allow you to pass the `use_list` param for that specific serializer. You will be able to do:

```
{
    'cache': "aiocache.RedisCache",
    'serializer': {
        'class': "aiocache.serializers.MessagePackSerializer",
        'use_list': False,
    },
    'plugins': [
        {'class': "aiocache.plugins.HitMissRatioPlugin"},
        {'class': "aiocache.plugins.TimingPlugin"}
    ],
}
```

Regarding `encoding`, thanks for the tip. But I want to avoid this:

```
>>> import msgpack
>>> msgpack.dumps('hola')
b'\xa4hola'
>>> msgpack.loads(b'\xa4hola')
b'hola'
```

If I encode a string, I want a string to be returned. Right now using `encoding` is the only way I've seen. In version 1.0 there is the `raw` one but not available in 0.5.1. Once 1.0 is released I'll update it

**Comment by ahopkins** [comment]
Thanks. I love the implementation. I guess I am used to getting the bytes string back having used `msgpack` in the past. I had to set `encoding=None` or else I was getting an error.

**Comment by argaen** [comment]
Glad its useful.

What do you mean by "getting an error"? `encoding=utf-8` is still a valid pattern in 0.5.1

**Comment by ahopkins** [comment]
Sorry for being vague. I worked through the exception and do not have it in
front of me. Effectively it was something like this:

UnicodeDecodeError: codec can't decode byte 0xde in position 0

**Comment by argaen** [comment]
Closing until we get more data to investigate
