### ISSUE TITLE
Allow lazy references to caches

### ISSUE THREAD

**Issue by jcugat** [argaen/aiocache#384]
In my use-case, I want to initialize the caches at class creation, but still be able to reference that cache in the decorators of the same class.

```py
class CachedClass:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, kwargs)
        caches.set_config({
            **caches.get_config(),
            'alt': {
                'cache': 'aiocache.SimpleMemoryCache',
            },
        })

    @cached(alias='alt')
    async def something_cached(self):
        return await do_stuff()
```

The downside I see if we allow this, is that missing caches would only be catched at runtime, for example:

```py
class CachedClass:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, kwargs)
        caches.set_config({
            **caches.get_config(),
            'alt': {
                'cache': 'aiocache.SimpleMemoryCache',
            },
        })

    @cached(alias='alt_with_typo')
    async def something_cached(self):
        return await do_stuff()
```

Since we are referencing a non-existing cache, we would only notice at the first call of the `something_cached` method.

**Comment by dreo** [comment]
More generally, it's not possible to import a class which has methods decorated by `cached` before configuring caches. I agree with the downside you mention, but from my point of view it's the lesser evil compared to e.g. lazy importing of a class (which is the only workaround I can think of now, but feel free to correct me).

**Comment by argaen** [comment]
Yup, that was my intention when I designed it. I prefer a startup error rather than runtime one. If there is an alternative that brings the best from both worlds, I'm open to it

**Comment by argaen** [comment]
I'm closing this issue as I prefer the actual behavior for now

**Comment by evgenybf** [comment]
> Yup, that was my intention when I designed it. I prefer a startup error rather than runtime one. If there is an alternative that brings the best from both worlds,

Sorry for bringing it up, but this doesn't work for the "default" cache, as it's always defined. If you add `@cashed` that refers to the default cache, and actual configuration is loaded too late, the decorator starts using a default memory cache without a warning.

Also, it seems that some examples in documentation for `@cached` are a bit misleading . E.g. https://aiocache.readthedocs.io/en/latest/decorators.html#cached
```python
@cached(
    ttl=10, cache=Cache.REDIS, key="key", serializer=PickleSerializer(),
    port=6379, namespace="main")
async def cached_call():
    return Result("content", 200)

def test_cached():
    cache = Cache(Cache.REDIS, endpoint="127.0.0.1", port=6379, namespace="main")
   ...
```
the cache in `@cashed` and the cache in `test_cached` are too different caches, and updating `endpoint` of the second one does nothing for first one.  This is not an error, but it may confuse users who are used to laziness of some ORM frameworks, where you define models first, but at the moment when they are instantiated, the most recently connection settings will be used.
