### ISSUE TITLE
Better way to add single entries to cache config

### ISSUE THREAD

**Issue by jcugat** [argaen/aiocache#385]
If I want to add a single new configuration cache without removing existing ones, I have to do some work in the `set_config()` call:

```py
caches.set_config({
    **caches.get_config(),
    'new_cache': {
        'cache': 'aiocache.SimpleMemoryCache',
        'namespace': 'new_namespace',
    },
})
```

What do you think about adding a new method, `add_config(name, <params>)` that just adds a new configuration cache?

```py
caches.add_config('new_cache', cache='aiocache.SimpleMemoryCache', namespace='new_namespace')
```

**Comment by argaen** [comment]
The way the factory/cache manager was thought originally was a way to set up a set of caches that would then later be used in the different services.

In general the pattern is:
1. Have a config file defining the caches you want
2. In app startup time call caches.set_config() with the whole configuration
3. Use the aliases later in the code

What's your use case? Are you initializing each alias in the service constructors? Is there a specific reason why you doing it this way?

**Comment by jcugat** [comment]
I have a project with several client libraries which are completely decoupled from the main app. It made sense to have their configuration separated, inside their own file, instead of the main app.

**Comment by argaen** [comment]
Then those caches are local to the services? Why don't you create the cache explicitly or using `caches.create`? No need to call `caches.set_config` and retrieve them with an alias.

Naming caches with an alias and storing their config with `caches.set_config` is in case you want to reuse them in any part of your code.
