### ISSUE TITLE
add warning in multi_cached docs about reusing keys

### ISSUE THREAD

**Issue by jcugat** [argaen/aiocache#388]
With the `@cached` decorator, there's no problem in using it with different methods since it will create different prefixes based on the method signature.

```py
@cached(alias='default')
async def foo1(self):
    return 1

@cached(alias='default')
async def foo2(self):
    return 2

assert await foo1() == 1
assert await foo2() == 2
```

I found a bit surprising that it's not the same for `@multi_cached`, this example will create clashing keys if the identifiers are the same:

```py
@multi_cached('entity_ids', alias='default')
async def multi1(self, entity_ids):
    return {num: num for num in entity_ids}

@multi_cached('entity_ids', alias='default')
async def multi2(self, entity_ids):
    return {num: num*2 for num in entity_ids}

# This works
assert await multi1(entity_ids=[1, 2]) == {1: 1, 2: 2}
# This would fail, since it would return the cached results from the previous call
assert await multi2(entity_ids=[1, 2]) == {1: 2, 2: 4}
```

**Comment by argaen** [comment]
In the case of cached, you are caching the function result while for multi_cached, you store each key from your `entity_ids` individually. The idea of this was that later in other parts of your code you could load those values easily doing `cache.get('entity_id')`.

This problem can be solved with https://github.com/argaen/aiocache/blob/master/aiocache/decorators.py#L200 and also if we implement https://github.com/argaen/aiocache/issues/387 by setting a different namespace for example.

**Comment by jcugat** [comment]
Oh, I understand the reasoning now. Maybe it's worth updating the documentation with this difference between the two.

**Comment by argaen** [comment]
Yup, worth to add a warning in the documentation of multi_cached. Will leave this issue as reminder to do so
