### ISSUE TITLE
key_builder does not receive function name

### ISSUE THREAD

**Issue by AFriemann** [argaen/aiocache#399]
Hi there,

is there a specific reason why the key_builder callable does not receive the function?

I'm running a python service with multiple processes and containers and would like to cache some function results globally, that means the default key doesn't quite cut it. However without the function name it is quite hard to find a unique name for keys.

If there is no particular reason for not handing over the function as it is done for the default key function I'd write up a PR later.

**Comment by AFriemann** [comment]
Or I'll just do it now

https://github.com/argaen/aiocache/issues/399

**Comment by argaen** [comment]
Nop, there is no specific reason :)

**Comment by argaen** [comment]
Fixed with https://github.com/argaen/aiocache/pull/417
