### ISSUE TITLE
diskcache backend support?

### ISSUE THREAD

**Issue by tehfink** [argaen/aiocache#402]
Very interesting project!

What do you think of supporting diskcache:
https://github.com/grantjenks/python-diskcache

**Comment by argaen** [comment]
Hi @tehfink. That's not possible right now because python-diskcache is synchronous. By integrating it it its operations would block the asyncio loop and it defeats the purpose of the library.

A disk backend could be implemented with https://github.com/Tinche/aiofiles though

**Comment by argaen** [comment]
Closing for now, going to open a new feature issue for implementing a disk cache backend (would be with aiofiles)
