### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by underyx** [argaen/aiocache#406]
The feature in https://github.com/argaen/aiocache/commit/6d95ea9d7698b49a5590132f14673f97f3edbefb has been merged as part of https://github.com/argaen/aiocache/pull/404 but not released. It's a super amazing cool feature though! 🦄🌈

Maybe it's time to publish a new release? 🙃

**Comment by argaen** [comment]
Sure, will try to do it this week if I find time :)

**Comment by underyx** [comment]
That's amazing, thank you so much!

**Comment by argaen** [comment]
Release 0.10.0

**Comment by underyx** [comment]
![yay](https://user-images.githubusercontent.com/1060436/41512614-355686b4-728c-11e8-9744-157d7707f018.gif)
