### ISSUE TITLE
Could you use getLogger(__name__) instead of getLogger(__file__)

### ISSUE THREAD

**Issue by mmamkin** [argaen/aiocache#411]
https://github.com/argaen/aiocache/blob/e2e8806f91893986ec98dde719b32b48937fe19c/aiocache/base.py#L10
It's unable to filter out log messages of this module with your current solution

**Comment by argaen** [comment]
Ops, sure. You want to provide MR for changing that? I see its the same in `__init__.py`, `decorators.py` and `serializers.py`

**Comment by mmamkin** [comment]
Done, https://github.com/argaen/aiocache/pull/412
Seems that's generally my first pull request in the open source world

**Comment by argaen** [comment]
congratulations then!

thanks for the contribution :)
