### ISSUE TITLE
Allow dynamic cache setup

### ISSUE THREAD

**Issue by jsoucheiron** [argaen/aiocache#421]
We have a library that does http requests and we've added aiocache to it. By default this library class uses an in-memory cache.
This works very well, but for one of our services we want to be able to change the backend to something else. Right now the only way is to manually replace the .cache object manually at `__init__` time.

We'd need to find an elegant solution to allow this kind of configuration overload for libraries.

**Comment by argaen** [comment]
I think https://github.com/argaen/aiocache/blob/master/aiocache/factory.py#L39 solves this as now you can just use a single constructor and provide a `url` for instantiating on type or another.
