### ISSUE TITLE
RedisCache sets wrong ttl value

### ISSUE THREAD

**Issue by rubik** [argaen/aiocache#427]
I initialized the cache with `cache = RedisCache(ttl=10)`, but when I set a value, e.g.
```
await cache.set('key', 'val')
```
it gets set with a ttl of 3600 for some reason. The problem seems to be here,
https://github.com/argaen/aiocache/blob/master/aiocache/backends/redis.py#L111
where the default ttl is not taken into account. The `BaseCache` class has a `ttl` argument so one expects the same to be true for `RedisCache` as well.

EDIT: Actually the bug is worse, since even `await cache.set('key', 'val', 10)` results in a ttl of 3600 in Redis.

**Comment by argaen** [comment]
```
import asyncio
from aiocache import RedisCache

async def main():
    cache = RedisCache(ttl=10)
    await cache.set('key', 'val')

if __name__ == '__main__':
    asyncio.run(main())
```

```
10:43 $ python qwe.py; redis-cli ttl key
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
(integer) 10            <=============
```

Unless you provide a snippet to reproduce I can't investigate further. Also according to what you're saying, tests like https://github.com/argaen/aiocache/blob/master/tests/acceptance/test_base.py#L74 should be failing, and they are not

**Comment by argaen** [comment]
Closing the issue as behavior is expected, feel free to reopen with more details in case you can provide a snippet to reproduce it :)
