### ISSUE TITLE
Next Release

### ISSUE THREAD

**Issue by oldani** [argaen/aiocache#442]
Hi, great work here.

Just one thing, docs are not on equal with the latest version on PyPI. I mean docs are updated with the latest code but this code is not available on PyPI. Any date for it?

**Comment by argaen** [comment]
Hey @oldani, in readthedocs you can select which version you want to read the docs from bottom left of the page.

<img width="295" alt="screen shot 2019-02-01 at 08 58 39" src="https://user-images.githubusercontent.com/3578154/52110022-9c427500-25ff-11e9-9413-501bacbbd3f0.png">

PS: Is there any specific feature you are missing or was about the docs? If its about the docs I'll close this
