### ISSUE TITLE
Give option to the user to NOT await for `cache.set` in decorators

### ISSUE THREAD

**Issue by Suor** [argaen/aiocache#445]
During normal work I get timeouts messages like this:

```python
Traceback (most recent call last):
  File "/home/suor/projects/aiocache/aiocache/decorators.py", line 108, in set_in_cache
    await self.cache.set(key, value, ttl=self.ttl)
  File "/home/suor/projects/aiocache/aiocache/base.py", line 58, in _enabled
    return await func(*args, **kwargs)
  File "/home/suor/projects/aiocache/aiocache/base.py", line 43, in _timeout
    return await asyncio.wait_for(func(self, *args, **kwargs), timeout)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

This is not stopping anything like exception should. I using cache cia `cached` decorator:
```python
def filecache(basedir):
    # Import from here since these are optional dependencies
    from aiocache import cached
    from aiocache.serializers import PickleSerializer
    from aiofilecache import FileCache

    return cached(cache=FileCache, serializer=PickleSerializer(),
                  basedir=basedir)

@filecache('some_dir')
@fetch(url, ...):
    # ...
    return response
```
`aiofilecache` is a simple file cache, you ca see [here](https://github.com/Suor/aiofilecache).

**Comment by argaen** [comment]
Hey @Suor if I understand your message, you mean you are getting the timeouts when they are not expected?

All caches come configured with a maximum timeout of 5 seconds, so if your function takes longer you are going to see this exception

**Comment by Suor** [comment]
The thing is I am not getting an exception, just garbage output. I don't know what should I do about it. 

Even if that were a proper exception not sure how I should handle that. Ignoring a timeout on `cache.set` looks safe, but once I get it function result is already lost probably.

**Comment by argaen** [comment]
Are you running this in a thread or a separate process? The exceptions is raised yes or yes as this is using `asyncio.wait_for` https://github.com/argaen/aiocache/blob/master/aiocache/base.py#L45. Its nothing specific from `aiocache`.

How you deal with those errors is up to you as it depends on the requirements of your application

**Comment by Suor** [comment]
No, no running in a thread. I am using `asyncio.gather()` on several tasks and seeing output like this sporadically.

**Comment by Suor** [comment]
> How you deal with those errors is up to you as it depends on the requirements of your application

Yes, but if, for example, I want to ignore `cache.set` timeout and just pass result I am out of luck when using `@cached`.

**Comment by argaen** [comment]
> No, not running in a thread. I am using asyncio.gather() on several tasks and seeing output like this sporadically.

With gather it depends on `return_exceptions` parameter: https://docs.python.org/3/library/asyncio-task.html#asyncio.gather

> Yes, but if, for example, I want to ignore cache.set timeout and just pass result I am out of luck when using @cached.

Ahhhh got you. Yes that indeed is a good point. I guess we could change the `await` or add a new param to control this behavior.

I'm renaming this issue in order to track this

**Comment by Suor** [comment]
> If return_exceptions is False (default), the first raised exception is immediately propagated to the task that awaits on gather(). Other awaitables in the aws sequence won’t be cancelled and will continue to run.

So an exception should propagate, which it does in many cases, but not in this one.

**Comment by argaen** [comment]
I've added the `aiocache_wait_for_write` param in the decorators.

> So an exception should propagate, which it does in many cases, but not in this one.

As said, this is not behavior responsible from aiocache, `wait_for` triggers an exception if it timeouts. ?`gather` lets you control whether you want to raise or return exceptions
