### ISSUE TITLE
@cached() swallows any exceptions in cache set

### ISSUE THREAD

**Issue by Suor** [argaen/aiocache#455]
I had unpicklable object buried somewhere in function result I was trying to cache and caching was silently skipped for me.

**Comment by argaen** [comment]
can you put a snippet to reproduce?

**Comment by argaen** [comment]
Also... do you really want to fail on setting the value in the cache? this would just make ignore the value that has been calculated and I don't think this is desirable. With just a warning on `failed to set the value in cache because of X` should be enough

**Comment by Suor** [comment]
From my point of view silencing IOErrors and such is ok, others are not.

Snippet:
```python
from aiocache import cached
from aiocache.base import BaseCache


class MyCache(BaseCache):
    async def _get(self, key, encoding="utf-8", _conn=None):
        return None

    async def _set(self, key, value, ttl=None, _cas_token=None, _conn=None):
        assert 0

@cached(cache=MyCache)
def func(x):
    return x

func(42)  # Should raise AssertionError
```

**Comment by argaen** [comment]
erm... 

1. The function must be `async`
2. Its not raising an exception because you have to await for the `func` to be run

This raises an exception
```
import asyncio

from aiocache import cached
from aiocache.base import BaseCache


class MyCache(BaseCache):
    async def _get(self, key, encoding="utf-8", _conn=None):
        return None

    async def _set(self, key, value, ttl=None, _cas_token=None, _conn=None):
        assert 0

@cached(cache=MyCache)
async def func(x):
    return x

asyncio.run(func(42))
```

**Comment by Suor** [comment]
Sorry for bad snippet, I still have this issue though. This is probably is about running under Django and its logging settings, can't reproduce it outside Django so far.

**Comment by argaen** [comment]
hmmm afaik Django is synchronous... So I don't think aiocache is compatible with it 🤔

**Comment by Suor** [comment]
I am running async scraping code inside Django command, so Djangos being synchronous doesn't matter. The thing is its environment somehow breaks things.

The obvious culprits are these lines:
```python
class cached:
    # ...
    async def set_in_cache(self, key, value):
        try:
            await self.cache.set(key, value, ttl=self.ttl)
        except Exception as e:
            logger.exception("Couldn't set %s in key %s, unexpected error", value, key)
```
Depending on something `logger.exception()` may raise or not.

**Comment by Suor** [comment]
So outside Django this code:
```python
import asyncio

from aiocache import cached
from aiocache.base import BaseCache


class MyCache(BaseCache):
    async def _get(self, key, encoding="utf-8", _conn=None):
        return None

    async def _set(self, key, value, ttl=None, _cas_token=None, _conn=None):
        assert 0


@cached(cache=MyCache)
async def func2(x):
    return x

async def func(x):
    res = await func2(x)
    print(res)


loop = asyncio.get_event_loop()
loop.run_until_complete(func(42))
```
swallows exception while still printing out message.

**Comment by argaen** [comment]
Yes, this is expected. The code: https://github.com/argaen/aiocache/blob/master/aiocache/decorators.py#L144

The rationale behind: Imagine the function takes 10 seconds to execute. If we would propagate the exception, you would lose the result. Its better to be able to retrieve the result even if trying to set the value in the cache fails. We don't want to affect behaviour if the cache is not working for some reason.

The message printed is with `logger.exception` so you have all traceback and everything needed to fix the issue on your side
