### ISSUE TITLE
Add Python3.8 in the pipeline

### ISSUE THREAD

**Issue by argaen** [argaen/aiocache#457]
- [ ] Check if it goes green (aiomcache maybe doesn't support it yet)
- [ ] Add it in README and setup

**Comment by drgarcia1986** [comment]
aioredis doesn't support py3.8 😢 
what about add [aredis](https://github.com/NoneGG/aredis) backend?

**Comment by argaen** [comment]
Closed by https://github.com/argaen/aiocache/pull/513

@drgarcia1986 tests pass with aioredis >=1.3.0. No thinking about changing backend right now
