### ISSUE TITLE
SimpleMemoryBackend() is counter-intuitive

### ISSUE THREAD

**Issue by keirlawson** [argaen/aiocache#465]
The current implementation of `SimpleMemoryBackend()` always returns a reference to the same class when callers might reasonably expect that it creates a new cache each time.   This confusion has lead to a bug in one of our libraries that uses SimpleMemoryBackend.  It would be great if it were possible to instead create multiple caches with the constructor.

**Comment by argaen** [comment]
So I've been thinking about this for a while. The original design of this library was to provide a caching framework with an interface that allows you to swap backend if needed so you expect the functionality to be the same regardless if you are using memcached, redis or memory. The rationale I followed when I did this for the memory backend is to treat it also as a remote server where you would be storing the data and if you need to differentiate you would use the `namespace` arg like you do with Redis and Memcached. So I prefer to keep this behavior. I'll add some explanation in the docstring of the class and will leave this open in case someone wants to chime in for more discussion on the topic
