### ISSUE TITLE
Add atomic flag

### ISSUE THREAD

**Issue by heckad** [argaen/aiocache#471]
Hello, everybody. I propose to add the atomic flag which should protect function from many calls. For example now this code print 10 lines with 'hi'
``` 
import asyncio

from aiocache import cached


@cached()
async def func():
    print('Hi')
    await asyncio.sleep(10)
    return 42


async def main():
    await asyncio.wait([func() for _ in range(10)])


asyncio.run(main())
```

If add atomic flag then should be to print one 'hi'

**Comment by argaen** [comment]
Have you read https://aiocache.readthedocs.io/en/latest/locking.html? I believe this is what you are looking for?
