### ISSUE TITLE
Use decorator on aiohttp route and not on a specific function

### ISSUE THREAD

**Issue by DaRoee** [argaen/aiocache#475]
Currently, the usage for caching routes is to decorate a function the route is using, though what can be really cool is caching the whole route response.
Using it as a decorator for the route is making the response fail...

I can implement it if you want, should be fairly quick and it's pretty much a requirement for my project :)

**Comment by argaen** [comment]
What's the failure? Could you post an example traceback? I'm also interested on what would be the changes required for this so feel free to open a quick PR and maybe we can discuss

**Comment by DaRoee** [comment]
My traceback is pretty generic, coming from nginx about a closed connection while reading the response header. 
The real problem can be understood here: https://docs.aiohttp.org/en/stable/faq.html#how-do-i-make-sure-my-custom-middleware-response-will-behave-correctly
We can't really reuse our cached response, so I think the solution will be to recreate aiohttp responses everytime the cache is called.
I'll do a PR later today/tomorrow, where we can further discuss about the solution :)

**Comment by argaen** [comment]
Closing as per https://github.com/argaen/aiocache/pull/476 discussion
