### ISSUE TITLE
Pytest compatibility

### ISSUE THREAD

**Issue by alvarogf97** [argaen/aiocache#484]
Hi there!

I'm trying to test my application which uses **aiocache** with redis, nevertheless I'm getting some errors when I execute my tests by using pytest:

```
/usr/local/lib/python3.7/asyncio/tasks.py:449: TimeoutError
------------------------------------------------- Captured log call -------------------------------------------------
WARNING  aioredis:pool.py:355 Connection <RedisConnection [db:1]> has pending commands, closing it.
----------------------------------------------- Captured log teardown -----------------------------------------------
ERROR    asyncio:base_events.py:1619 Task was destroyed but it is pending!
task: <Task pending coro=<RedisConnection._read_data() running at /usr/local/lib/python3.7/site-packages/aioredis/connection.py:186> wait_for=<Future cancelled> cb=[RedisConnection.__init__.<locals>.<lambda>() at /usr/local/lib/python3.7/site-packages/aioredis/connection.py:168]>
```

There's something that I need to configure before launch my tests? thanks!

**Comment by argaen** [comment]
Hey @alvarogf97, nope, aiocache and pytest are compatible, in fact the test suite for aiocache is written with it. Seeing the TimeoutError, seems it is something with your test, maybe you are not mocking Redis? or you are trying to hit redis but it is not reachable or not running

**Comment by alvarogf97** [comment]
@argaen I'm executting pytest inside docker by using compose so I do not have to mock redis, in addition both containers are in the same network and the application works perfectly in local. I solved this issue by setting **AIOCACHE_DISABLE** to 1. Have you got any idea of what is happening? Thanks!

**Comment by ecly** [comment]
Sorry for bumping this, but I feel as though this might be related. I am indeed running a local dockerized redis instance as well, that I use to run some of my tests with locally. At the end of my pytest execution (with all tests passing), I get the following printed.

```
task: <Task pending name='Task-6' coro=<RedisConnection._read_data() running at /home/ecly/Programming/work/mlt-mt-api/.venv/lib/python3.8/site-packages/aioredis/connection.py:186> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fe8c81b9af0>()]> cb=[RedisConnection.__init__.<locals>.<lambda>() at /home/ecly/Programming/work/mlt-mt-api/.venv/lib/python3.8/site-packages/aioredis/connection.py:168]>
```

@argaen let me know if you think this is unrelated, or if you have an idea what the problem might be.

**Comment by ecly** [comment]
Explicitly starting, and closing initializing the cache connection at the start of a test and closing it at the end using a fixture resolves my comment above. Although I'm not sure it's the cleanest solution, and also not one that I necessarily fully understand.
