### ISSUE TITLE
Some functionality like get_all

### ISSUE THREAD

**Issue by csajedi** [argaen/aiocache#485]
I am really wanting to use aiocache with fastapi, but my caching problem centers around a pattern where many values are kept, then all processed simultaneously. Is there any way to get all the values in a cache as a useful iterable datastructure before using something clear() to empty the cache?

**Comment by paulo-raca** [comment]
Sounds useful for debugging

**Comment by argaen** [comment]
Hey @csajedi not all caches implement a function to return all keys that are currently stored. For your use case, you should keep somewhere the list of keys you want to interact with and then you can use `multi_get` to retrieve all those values at the same time.
