### ISSUE TITLE
Does this project support semantic versioning?

### ISSUE THREAD

**Issue by alvassin** [argaen/aiocache#491]
What is the best way to specify this project in requirements? Can i use this project with ~= operator and specify it like `aiocache~=0.11.1`?

From one hand, this library has early version, but from another, i see that some files are 3 years old, so it looks pretty mature. So, does this project follow [semver](https://semver.org), where version consists of the MAJOR.MINOR.PATCH segments (described below)? 
- `MAJOR` for incompatible API changes,
- `MINOR` for new functionality in a backwards compatible manner
- `PATCH` version when you make backwards compatible bug fixes

If it is, don't you mind to add this information to README/CHANGELOG (so, others could find answer for this question quickly)?

**Comment by argaen** [comment]
Hey @alvassin, yes we try to follow semver.
