### ISSUE TITLE
how to use keybuilder in cache constructor

### ISSUE THREAD

**Issue by mt-vasu-sharma** [argaen/aiocache#500]
I had gone through the documentation and my use case is to cache the results by one of the arguments in the coroutine. Suppose my function is :- func(id, s_id, sep_id) -> str . My use case is to store the result of this function with the key as sep_id and also have a ttl with each key-value pair (the ttl value is same for all key value pairs). Can you give an example of how do I achieve this using the decorated construction of cache?

**Comment by argaen** [comment]
https://github.com/argaen/aiocache/blob/634348f40ce8caa01c7c35010acf32d8c3e17ba6/tests/acceptance/test_decorators.py#L43
