### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by fabaff** [argaen/aiocache#504]
Asynctest doesn't work with Python 3.8 and above.

Asynctest upstream is aware of this breakage and recommends using the built-in AsyncMock instead.

See also Martiusweb/asynctest#144 and Martiusweb/asynctest#126

**Comment by argaen** [comment]
Hmmm interesting, that's probably why the python3.8 branch tests didn't work. However it's not that easy as we still want to run tests for 3.7, 3.6 versions so would have to have a way to have both when running the test suite

**Comment by JeppeKlitgaard** [comment]
I believe there are packages that implement the AsyncMock interface for Python 3.6 and Python 3.7, so we wouldn't need to mess around with two different approaches.

https://pypi.org/project/asyncmock/ seems to do this, but a better approach would probably be to use the backported `mock 4.X` package: https://pypi.org/project/mock/

**Comment by argaen** [comment]
https://github.com/argaen/aiocache/pull/513 added python3.8 to the pipeline and tests seem to run and pass so closing for now.
