### ISSUE TITLE
Can caches config be used with cached decorator? How?

### ISSUE THREAD

**Issue by lk-jeffpeck** [argaen/aiocache#506]
Perhaps I am not understanding something from the documentation, but please excuse me if this question does not belong here.

I am trying to find the most appropriate way to use a config with the `@cached()` decorator.

Thanks!

**Comment by argaen** [comment]
https://aiocache.readthedocs.io/en/latest/decorators.html

Check the `alias` parameter and give it a try

**Comment by lk-jeffpeck** [comment]
Thanks, that makes perfect sense!

So, I could picture a use-case where I have two configs:
- default: `aiocache.SimpleMemoryCache`
- redis_alt: `aiocache.RedisCache`

and I can have my decorators as:
```
@cached(alias=CACHE_CONFIG_ALIAS)
```

and depending on whether or not a redis config is specified, etc. will set `CACHE_CONFIG_ALIAS` to either `default` or `REDIS_ALT`.

Does that sound right?

---

Also, one thing that I noticed with this (and maybe should be a separate issue) is that for my key builder, if I specify like this:
```
@cached(alias='redis_alt', key_builder=my_cache_key_builder)
```

The function gets `*args`.

But, if I specify in the config:
```
...

        'key_builder': my_cache_key_builder,
...
```

then the `my_cache_key_builder` gets a tuple with all of the args as the first arg.

That was the first thing that made me wonder whether I am doing this in the "right" way, hence coming here to ask.

Thanks!

**Comment by lk-jeffpeck** [comment]
Oh, I think I see what is happening. The key_builder is getting called twice.

So, my custom key builder from the decorator (which returns a tuple) is being passed into itself a second time when I declare it a second time inside the config.

But, it looks like if I remove it from the decorator (as I intend to do), it will then resort to the default key builder from the constructor and pass that string into the config key builder. Hrm.

**Comment by lk-jeffpeck** [comment]
I see how this actually makes sense.

There is the key_builder for the decorator function and then there is the general key builder for the cache config, which may be used to optionally modify the key for the cache that it is going into.
